version: "3"

services:
  api:
    build: ./
    volumes:
      - ./:/go/src/app/
    ports:
      - "8080:8080"
    tty: true
  db:
    image: postgres:14.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sampledb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      TZ: "Asia/Tokyo"
