// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/h-masano/ent-api-sample/database/ent/schema"
	"github.com/h-masano/ent-api-sample/database/ent/users"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	usersFields := schema.Users{}.Fields()
	_ = usersFields
	// usersDescAge is the schema descriptor for age field.
	usersDescAge := usersFields[0].Descriptor()
	// users.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	users.AgeValidator = usersDescAge.Validators[0].(func(int) error)
	// usersDescName is the schema descriptor for name field.
	usersDescName := usersFields[1].Descriptor()
	// users.DefaultName holds the default value on creation for the name field.
	users.DefaultName = usersDescName.Default.(string)
}
